[package]
name = "ocode-desktop"
version = "0.1.1"
description = "Desktop shell for ocode"
authors = ["ocode contributors"]
edition = "2021"

[lib]
name = "ocode_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde_json = "1"
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
