import type { InlineHtmlContentBlock } from "@anvil/protocol";
import {
  CodeIcon,
  Maximize01Icon,
  Minimize01Icon,
  ReloadIcon,
} from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { useEffect, useMemo, useRef, useState } from "react";

import { Spinner } from "./ui/spinner";

const MESSAGE_TYPE = "ocode:inline-html";
const COLLAPSED_MAX_HEIGHT = 640;
const EXPANDED_MAX_HEIGHT = 1_100;

function randomToken(): string {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

function encodeMarkup(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (let offset = 0; offset < bytes.length; offset += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000));
  }
  return btoa(binary);
}

function documentInjection(token: string, html: string): string {
  const serializedToken = JSON.stringify(token).replace(/</g, "\\u003c");
  const encodedHtml = encodeMarkup(html);
  return `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; base-uri 'none'; object-src 'none'; frame-src 'none'; form-action 'none'; connect-src 'none'; navigate-to 'none'; img-src data: blob:; media-src data: blob:; font-src data:; style-src 'unsafe-inline'; script-src 'nonce-${token}'">
<meta name="referrer" content="no-referrer">
<style>
  :root { color-scheme: light dark; }
  html, body { min-height: 0; margin: 0; background: transparent !important; }
  body { overflow-wrap: anywhere; }
  @media (prefers-reduced-motion: reduce) {
    *, *::before, *::after { scroll-behavior: auto !important; animation-duration: 0.01ms !important; animation-iteration-count: 1 !important; transition-duration: 0.01ms !important; }
  }
</style>
<script nonce="${token}">
(() => {
  const token = ${serializedToken};
  const install = () => {
    const encodedMarkup = ${JSON.stringify(encodedHtml)};
  const bytes = Uint8Array.from(atob(encodedMarkup), character => character.charCodeAt(0));
  const generated = new TextDecoder().decode(bytes);
  const parsed = new DOMParser().parseFromString(generated, "text/html");
  parsed.querySelectorAll("script, iframe, frame, object, embed, base, meta[http-equiv]").forEach(element => element.remove());
  parsed.querySelectorAll("*").forEach(element => {
    for (const attribute of [...element.attributes]) {
      if (/^on/i.test(attribute.name)) element.removeAttribute(attribute.name);
    }
  });
  parsed.querySelectorAll("a, area").forEach(element => {
    element.removeAttribute("href");
    element.removeAttribute("target");
    element.removeAttribute("ping");
  });
  parsed.querySelectorAll("form").forEach(element => element.removeAttribute("action"));
  parsed.querySelectorAll("[formaction]").forEach(element => element.removeAttribute("formaction"));
  const fragment = document.createDocumentFragment();
  parsed.head.querySelectorAll("style").forEach(style => fragment.append(document.importNode(style, true)));
  for (const node of [...parsed.body.childNodes]) fragment.append(document.importNode(node, true));
  document.body.append(fragment);
  document.addEventListener("click", event => {
    if (event.target instanceof Element && event.target.closest("a, area")) event.preventDefault();
  });
  document.addEventListener("submit", event => event.preventDefault());

  const post = (event, extra = {}) => parent.postMessage({ type: ${JSON.stringify(MESSAGE_TYPE)}, token, event, ...extra }, "*");
  const height = () => Math.max(
    document.documentElement?.scrollHeight || 0,
    document.body?.scrollHeight || 0,
    document.documentElement?.offsetHeight || 0,
    document.body?.offsetHeight || 0
  );
  const reportSize = () => post("resize", { height: Math.ceil(height()) });
  const ready = () => {
    post("ready");
    reportSize();
    if (typeof ResizeObserver !== "undefined") new ResizeObserver(reportSize).observe(document.documentElement);
    else setInterval(reportSize, 500);
  };
  window.addEventListener("message", event => {
    const data = event.data;
    if (event.source === parent && data?.type === ${JSON.stringify(MESSAGE_TYPE)} && data.token === token && data.event === "measure") reportSize();
  });
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", ready, { once: true });
  else ready();
  window.addEventListener("load", reportSize, { once: true });
  };
  if (document.body) install();
  else document.addEventListener("DOMContentLoaded", install, { once: true });
})();
</script>`;
}

export function buildInlineHtmlDocument(html: string, token: string): string {
  // Generated bytes remain inert base64 until the trusted nonce-bearing bridge has
  // installed the CSP and stripped navigation, executable markup, and event handlers.
  return `<!doctype html><html><head>${documentInjection(token, html)}</head><body></body></html>`;
}

export function SandboxedHtmlPreview({ html, title, className = "" }: {
  html: string;
  title: string;
  className?: string;
}) {
  const frameRef = useRef<HTMLIFrameElement>(null);
  const token = useMemo(() => randomToken(), [html]);
  const source = useMemo(() => buildInlineHtmlDocument(html, token), [html, token]);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  useEffect(() => {
    setState("loading");
    const timeout = window.setTimeout(() => setState("error"), 8_000);
    const receive = (event: MessageEvent) => {
      if (event.source !== frameRef.current?.contentWindow) return;
      const data = event.data;
      if (!data || typeof data !== "object" || data.type !== MESSAGE_TYPE || data.token !== token) return;
      if (data.event === "ready" || data.event === "resize") {
        window.clearTimeout(timeout);
        setState("ready");
      }
    };
    window.addEventListener("message", receive);
    return () => {
      window.clearTimeout(timeout);
      window.removeEventListener("message", receive);
    };
  }, [token]);
  return (
    <div className={`sandboxed-html-preview sandboxed-html-preview--${state} ${className}`.trim()}>
      {state === "loading" && <div className="inline-html-artifact-loading" role="status"><Spinner className="size-4" />Loading preview…</div>}
      {state === "error" && <div className="inline-html-artifact-error" role="alert">HTML preview could not be rendered.</div>}
      <iframe
        ref={frameRef}
        className="sandboxed-html-preview-frame"
        sandbox="allow-scripts"
        referrerPolicy="no-referrer"
        srcDoc={source}
        title={title}
        onLoad={() => frameRef.current?.contentWindow?.postMessage({ type: MESSAGE_TYPE, token, event: "measure" }, "*")}
        onError={() => setState("error")}
      />
    </div>
  );
}

export function InlineHtmlArtifactPending({ title }: { title: string }) {
  return (
    <article className="inline-html-artifact inline-html-artifact--pending" aria-label={title}>
      <div className="inline-html-artifact-title"><strong>{title}</strong></div>
      <div className="inline-html-artifact-loading" role="status" aria-live="polite">
        <Spinner className="size-4" />
        <span>Building preview…</span>
      </div>
    </article>
  );
}

export function InlineHtmlArtifact({ block }: { block: InlineHtmlContentBlock }) {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [reloadKey, setReloadKey] = useState(0);
  const [renderState, setRenderState] = useState<"loading" | "ready" | "error">("loading");
  const [naturalHeight, setNaturalHeight] = useState(180);
  const [showSource, setShowSource] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const token = useMemo(() => randomToken(), [block.id, reloadKey]);
  const source = useMemo(() => buildInlineHtmlDocument(block.html, token), [block.html, token]);
  const frameHeight = Math.max(120, Math.min(naturalHeight, expanded ? EXPANDED_MAX_HEIGHT : COLLAPSED_MAX_HEIGHT));

  useEffect(() => {
    const timeout = window.setTimeout(() => {
      setRenderState((state) => state === "loading" ? "error" : state);
    }, 8_000);
    let measureAttempts = 0;
    const requestMeasure = () => {
      if (measureAttempts++ >= 20) {
        window.clearInterval(measureInterval);
        return;
      }
      iframeRef.current?.contentWindow?.postMessage({ type: MESSAGE_TYPE, token, event: "measure" }, "*");
    };
    const measureInterval = window.setInterval(requestMeasure, 100);
    const receive = (event: MessageEvent) => {
      if (event.source !== iframeRef.current?.contentWindow) return;
      const data = event.data;
      if (!data || typeof data !== "object" || data.type !== MESSAGE_TYPE || data.token !== token) return;
      if (data.event === "ready") {
        window.clearTimeout(timeout);
        setRenderState("ready");
      }
      if (data.event === "resize" && typeof data.height === "number" && Number.isFinite(data.height)) {
        window.clearTimeout(timeout);
        window.clearInterval(measureInterval);
        setRenderState("ready");
        setNaturalHeight(Math.max(1, Math.ceil(data.height)));
      }
    };
    window.addEventListener("message", receive);
    requestMeasure();
    return () => {
      window.clearTimeout(timeout);
      window.clearInterval(measureInterval);
      window.removeEventListener("message", receive);
    };
  }, [token]);

  const reload = () => {
    setRenderState("loading");
    setReloadKey((value) => value + 1);
  };

  return (
    <article className={`inline-html-artifact inline-html-artifact--${renderState}${expanded ? " inline-html-artifact--expanded" : ""}`}>
      <header className="inline-html-artifact-header">
        <span className="inline-html-artifact-title">
          <strong>{block.title}</strong>
          {block.sourcePath && <small>{block.sourcePath}</small>}
        </span>
        <span className="inline-html-artifact-actions">
          <button type="button" onClick={() => setShowSource((value) => !value)} aria-pressed={showSource} title={showSource ? "Hide source" : "Show source"}>
            <HugeiconsIcon icon={CodeIcon} strokeWidth={2} className="size-3.5" />
            <span className="sr-only">{showSource ? "Hide source" : "Show source"}</span>
          </button>
          <button type="button" onClick={reload} title="Reload preview">
            <HugeiconsIcon icon={ReloadIcon} strokeWidth={2} className="size-3.5" />
            <span className="sr-only">Reload preview</span>
          </button>
          <button type="button" onClick={() => setExpanded((value) => !value)} aria-pressed={expanded} title={expanded ? "Collapse preview" : "Expand preview"}>
            <HugeiconsIcon icon={expanded ? Minimize01Icon : Maximize01Icon} strokeWidth={2} className="size-3.5" />
            <span className="sr-only">{expanded ? "Collapse preview" : "Expand preview"}</span>
          </button>
        </span>
      </header>
      <div className="inline-html-artifact-canvas" style={{ height: frameHeight }}>
        {renderState === "loading" && (
          <div className="inline-html-artifact-loading" role="status" aria-live="polite">
            <Spinner className="size-4" />
            <span>Connecting to preview…</span>
          </div>
        )}
        {renderState === "error" && (
          <div className="inline-html-artifact-error" role="alert">
            <span>Preview did not connect.</span>
            <button type="button" onClick={reload}>Try again</button>
          </div>
        )}
        <iframe
          key={reloadKey}
          ref={iframeRef}
          className="inline-html-artifact-frame"
          sandbox="allow-scripts"
          referrerPolicy="no-referrer"
          srcDoc={source}
          title={block.title}
          onLoad={() => setRenderState("ready")}
          onError={() => setRenderState("error")}
        />
      </div>
      {showSource && <pre className="inline-html-artifact-source"><code>{block.html}</code></pre>}
    </article>
  );
}
